// Mock 数据
import type { User, Project, ProjectStats } from '@/types';

// Mock 用户数据
export const MOCK_USERS = {
  admin: {
    id: 'user-admin-001',
    username: 'admin',
    email: 'admin@example.com',
    password: 'admin123', // 实际应用中应该加密
    fullName: '系统管理员',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    role: 'admin' as const,
    department: '技术部',
    phone: '13800138000',
    status: 'active' as const,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  pm: {
    id: 'user-pm-001',
    username: 'pm',
    email: 'pm@example.com',
    password: 'pm123',
    fullName: '项目经理',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pm',
    role: 'project_manager' as const,
    department: '项目部',
    phone: '13800138001',
    status: 'active' as const,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  dev: {
    id: 'user-dev-001',
    username: 'dev',
    email: 'dev@example.com',
    password: 'dev123',
    fullName: '开发工程师',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dev',
    role: 'developer' as const,
    department: '技术部',
    phone: '13800138002',
    status: 'active' as const,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  user: {
    id: 'user-user-001',
    username: 'user',
    email: 'user@example.com',
    password: 'user123',
    fullName: '普通用户',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user',
    role: 'user' as const,
    department: '业务部',
    phone: '13800138003',
    status: 'active' as const,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
};

// Mock 项目数据
export const MOCK_PROJECTS: Project[] = [
  {
    id: 'project-001',
    name: '数据仓库优化项目',
    type: 'data_development',
    description: '优化现有数据仓库架构，提升查询性能，降低存储成本',
    priority: 'high',
    status: 'in_progress',
    submitterId: 'user-user-001',
    submitterName: '普通用户',
    ownerId: 'user-dev-001',
    ownerName: '开发工程师',
    participantIds: ['user-dev-001', 'user-pm-001'],
    estimatedStartDate: new Date('2024-01-10'),
    estimatedEndDate: new Date('2024-03-10'),
    actualStartDate: new Date('2024-01-15'),
    actualEndDate: undefined,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-02-01'),
    remarks: '需要注意数据迁移的风险',
    attachments: [
      {
        id: 'attach-001',
        fileName: '需求文档.pdf',
        fileUrl: 'https://example.com/files/001.pdf',
        fileSize: 1024000,
        fileType: 'application/pdf',
        uploadedAt: new Date('2024-01-05'),
        uploadedBy: 'user-user-001',
      },
    ],
    tags: ['重要', '紧急', '数据'],
  },
  {
    id: 'project-002',
    name: '用户管理系统升级',
    type: 'system_development',
    description: '升级用户管理系统，增加权限管理、审计日志等功能',
    priority: 'medium',
    status: 'pending_review',
    submitterId: 'user-pm-001',
    submitterName: '项目经理',
    ownerId: undefined,
    ownerName: undefined,
    participantIds: [],
    estimatedStartDate: new Date('2024-02-01'),
    estimatedEndDate: new Date('2024-04-01'),
    actualStartDate: undefined,
    actualEndDate: undefined,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    remarks: '',
    attachments: [],
    tags: ['系统', '升级'],
  },
  {
    id: 'project-003',
    name: '数据报表开发',
    type: 'data_development',
    description: '开发销售数据分析报表，支持多维度数据查询和可视化展示',
    priority: 'urgent',
    status: 'submitted',
    submitterId: 'user-user-001',
    submitterName: '普通用户',
    ownerId: undefined,
    ownerName: undefined,
    participantIds: [],
    estimatedStartDate: new Date('2024-02-15'),
    estimatedEndDate: new Date('2024-03-15'),
    actualStartDate: undefined,
    actualEndDate: undefined,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
    remarks: '需要在月底前完成',
    attachments: [],
    tags: ['紧急', '报表'],
  },
  {
    id: 'project-004',
    name: '移动端APP开发',
    type: 'system_development',
    description: '开发公司内部移动办公APP',
    priority: 'high',
    status: 'in_progress',
    submitterId: 'user-admin-001',
    submitterName: '系统管理员',
    ownerId: 'user-dev-001',
    ownerName: '开发工程师',
    participantIds: ['user-dev-001'],
    estimatedStartDate: new Date('2024-01-01'),
    estimatedEndDate: new Date('2024-06-01'),
    actualStartDate: new Date('2024-01-05'),
    actualEndDate: undefined,
    createdAt: new Date('2023-12-20'),
    updatedAt: new Date('2024-02-01'),
    remarks: '第一期功能开发中',
    attachments: [],
    tags: ['移动端', 'APP'],
  },
  {
    id: 'project-005',
    name: '数据清洗工具开发',
    type: 'data_development',
    description: '开发自动化数据清洗工具，提升数据质量',
    priority: 'low',
    status: 'completed',
    submitterId: 'user-pm-001',
    submitterName: '项目经理',
    ownerId: 'user-dev-001',
    ownerName: '开发工程师',
    participantIds: ['user-dev-001'],
    estimatedStartDate: new Date('2023-11-01'),
    estimatedEndDate: new Date('2023-12-31'),
    actualStartDate: new Date('2023-11-05'),
    actualEndDate: new Date('2023-12-28'),
    createdAt: new Date('2023-10-25'),
    updatedAt: new Date('2023-12-28'),
    remarks: '已完成并上线',
    attachments: [],
    tags: ['数据', '工具'],
  },
];

// Mock 统计数据
export const MOCK_STATS: ProjectStats = {
  total: MOCK_PROJECTS.length,
  submitted: MOCK_PROJECTS.filter((p) => p.status === 'submitted').length,
  pendingReview: MOCK_PROJECTS.filter((p) => p.status === 'pending_review').length,
  inProgress: MOCK_PROJECTS.filter((p) => p.status === 'in_progress').length,
  completed: MOCK_PROJECTS.filter((p) => p.status === 'completed').length,
  dataProjects: MOCK_PROJECTS.filter((p) => p.type === 'data_development').length,
  systemProjects: MOCK_PROJECTS.filter((p) => p.type === 'system_development').length,
};

// Mock Token
export const generateMockToken = (username: string) => {
  return `mock-token-${username}-${Date.now()}`;
};
